#![cfg_attr(target_family = "wasm", no_std)]
// Uniswap-style swap entrypoints legitimately take a full set of params
// (path, amounts, recipient, deadline); the lint also fires on the
// contractclient code generated by the #[contractimpl] macro.
#![allow(clippy::too_many_arguments)]
mod contract;
mod helpers;
mod storage;

pub use contract::RouterContract;

#[cfg(any(test, feature = "testutils"))]
pub use contract::RouterContractClient;
